# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: shpool1

steps:
  - checkout: self
    persistCredentials: true   # this must be set to extract the GitHub token
  - script: |
      cat ./.git/config
    displayName: 'Cat git config file' 
  - bash: |
        extraheader_line=$(grep -oP 'extraheader = AUTHORIZATION: basic \K.*' ./.git/config) 
        if [ -n "$extraheader_line" ]; then echo "Extracted token: $extraheader_line" else echo "No extraheader token found" fi
  - bash: |
        # mkdir $(Build.SourcesDirectory)/testprv1
        #cd $(Build.SourcesDirectory)/testprv1
        pwd
  - bash: |
      # git clone https://$(GITHUB_TOKEN)@github.com/devsecopstest1/testprv1.git
    displayName: "git clone"


