# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: shpool1

steps:
  - checkout: self
    persistCredentials: true   # this must be set to extract the GitHub token
  - bash: |
      export remote_url=$(git config remote.origin.url)
      export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
      export remote_auth_token_decode=$(base64 --decode <<< $remote_auth_token)
      echo "##vso[task.setvariable variable=GITHUB_TOKEN;]$remote_auth_token_decode"
      mkdir $(Build.SourcesDirectory)/testprv1
      workingDirectory: $(Build.SourcesDirectory)/testprv1
    displayName: "Set GITHUB_TOKEN"
  - bash: |
      git clone https://$(GITHUB_TOKEN)@github.com/testprv1 .
    displayName: "git clone"


